### ISSUE TITLE
issue about pdb data

### ISSUE THREAD

**Issue by Leafaeolian** [myprecioushh/ZeroBind#1]
hi author ,thank for your great work, but i  encountered the following error during the reproduction process. Does this mean that I need the /tmp folder, but I did not find the relevant resources?

 File "/zerobind/ZeroBind/protein_pretrain.py", line 59, in protein_graph
    g = construct_graph(config=config, path=str(protein_path)+str(pdb_ID)+".pdb")
  File "/zerobind/lib/python3.9/site-packages/graphein/protein/graphs.py", line 801, in construct_graph
    raw_df = read_pdb_to_dataframe(
  File "/zerobind/lib/python3.9/site-packages/graphein/protein/graphs.py", line 106, in read_pdb_to_dataframe
    atomic_df = PandasPdb().read_pdb(path)
  File "/zerobind/lib/python3.9/site-packages/biopandas/pdb/pandas_pdb.py", line 95, in read_pdb
    self.pdb_path, self.pdb_text = self._read_pdb(path=str(path))
  File "/zerobind/lib/python3.9/site-packages/biopandas/pdb/pandas_pdb.py", line 404, in _read_pdb
    with openf(path, r_mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/zerobind/ZeroBind/tmp/P42336.pdb'

**Comment by 1412140736** [comment]
Is your problem solved? I encountered such a problem, is there any solution?

Traceback (most recent call last):
  File "E:\AAstudy\a研究生\组会\ZeroBind-main\ZeroBind-main\metaentry.py", line 3, in <module>
    from GCNmodel import GCN_DTIMAML
  File "E:\AAstudy\a研究生\组会\ZeroBind-main\ZeroBind-main\GCNmodel.py", line 17, in <module>
    from protein_pretrain import pretrain_init
  File "E:\AAstudy\a研究生\组会\ZeroBind-main\ZeroBind-main\protein_pretrain.py", line 118, in <module>
    protein_graphs=trainandtest()
  File "E:\AAstudy\a研究生\组会\ZeroBind-main\ZeroBind-main\protein_pretrain.py", line 93, in trainandtest
    protein_graphs[protein_ID] = protein_graph(protein_path, protein_ID)
  File "E:\AAstudy\a研究生\组会\ZeroBind-main\ZeroBind-main\protein_pretrain.py", line 59, in protein_graph
    g = construct_graph(config=config, pdb_path=str(protein_path)+str(pdb_ID)+".pdb")
TypeError: construct_graph() got an unexpected keyword argument 'pdb_path'

**Comment by Liuyujian0408** [comment]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\python\molecular related\ZeroBind-main\GCNmodel.py", line 17, in <module>
    from protein_pretrain import pretrain_init
  File "E:\python\molecular related\ZeroBind-main\protein_pretrain.py", line 129, in <module>
    protein_graphs=trainandtest()
  File "E:\python\molecular related\ZeroBind-main\protein_pretrain.py", line 104, in trainandtest
    protein_graphs[protein_ID] = protein_graph(protein_path, protein_ID)
  File "E:\python\molecular related\ZeroBind-main\protein_pretrain.py", line 59, in protein_graph
    g = construct_graph(config=config, pdb_path=str(protein_path)+str(pdb_ID)+".pdb")
TypeError: construct_graph() got an unexpected keyword argument 'pdb_path'
